
# 기본 애플리케이션 설정
spring:
  mvc:
    throw-exception-if-no-handler-found: false
  web:
    resources:
      add-mappings: true

  application:
    name: stockroom-sns

  profiles:
    active: local

  # JPA 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    open-in-view: false

  # 데이터소스 기본 설정 (profile별로 오버라이드)
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000

  # OAuth2 기본 설정 (profile별로 오버라이드)
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile

  # Jackson 설정
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 서버 설정
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  forward-headers-strategy: native

# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}

# API 문서화 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# 로깅 설정
logging:
  level:
    root: INFO
    com.stockroom.sns: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 애플리케이션 설정
app:
  auth:
    token-secret: ${JWT_SECRET:ThisIsADefaultSecretKeyForDevelopmentOnly12345}
    token-expiry: 86400000 # 1 day in milliseconds
    refresh-token-expiry: 604800000 # 7 days in milliseconds
  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-headers: "*"
    exposed-headers: Authorization
    allow-credentials: true
    max-age: 3600
  oauth2:
    authorized-redirect-uris: http://localhost:3000/oauth2/redirect,http://localhost:5173/oauth2/redirect
